name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build green-lisp
      uses: mohe2015/racket-package-ci-action@master
      with:
        name: green-lisp

